---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Roze.
--- DateTime: 2020-09-08 23:22
---

event.ignoreAll()
event.clear()

filesystem.initFileSystem("/dev")

drive = ""
for _,f in pairs(filesystem.childs("/dev")) do
    if not (f == "serial") then
        drive = f
        break
    end
end
filesystem.mount("/dev/" .. drive, "/")

dev = component.proxy("0FB7C81A4D8ACBDB97B3D3BAE8F8A507")

storages = {
    {
        container = component.proxy("96BC0B394EC92255247E9AA0AE8FA65E"),
        busName = "Puller_A_Canisters",
        resource = "Empty Canister",
        maintain = 600,
        treshold = 50
    }
}



filesystem.doFile("/Common.lua")
--filesystem.doFile("/Screen.lua")
filesystem.doFile("/BarrowComputer.lua")